name: kitchenowl
description: KitchenOwl helps you organize your grocery life.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.20+91

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  collection: ^1.17.1
  path_provider: ^2.0.14
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.2
  animations: ^2.0.7
  shimmer: ^3.0.0
  equatable: ^2.0.5
  url_launcher: ^6.1.10
  flutter_custom_tabs: ^1.2.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  http: ^1.1.2
  diffutil_dart: ^4.0.0

  responsive_builder: ^0.7.0
  dynamic_color: ^1.6.3

  azlistview_plus: ^3.0.0
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  tuple: ^2.0.1
  community_charts_flutter: ^1.0.2
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  share_handler: ^0.0.19
  share_plus: ^7.2.1
  reorderables: ^0.6.0
  flutter_colorpicker: ^1.0.3
  sliver_tools: ^0.2.12
  go_router: ^12.1.1
  socket_io_client: ^2.0.3+1
  fraction: ^5.0.2
  flutter_blurhash: ^0.8.2
  transparent_image: ^2.0.1
  universal_html: ^2.2.4
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.5
  flutter_native_splash: ^2.3.5

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Localization generation
  generate: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Items
      fonts:
        - asset: fonts/Items.ttf

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon/icon-small.png"
      adaptive_background_color: '#20AC64'
      adaptive_foreground_image: "assets/icon/icon-foreground.png"
      adaptive_round_image: "assets/icon/icon-foreground.png"
      adaptive_monochrome_image: "assets/icon/icon-foreground.png"
    ios:
      enable: true
      image_path: "assets/icon/icon-small.png"
    web:
      enable: true
      image_path: "assets/icon/icon.png"
      favicon_path: "assets/icon/icon-rounded.png"
    macos:
      enable: true
      image_path: "assets/icon/icon.png"
    windows:
      enable: true
      image_path: "assets/icon/icon-rounded.png"

flutter_native_splash:
  color: "#fafafa"
  # image: assets/splash.png
  color_dark: "#303030"
  # image_dark: assets/splash-invert.png
  android_12:
    color: "#fafafa"
    color_dark: "#303030"
