name: kitchenowl
description: KitchenOwl helps you organize your grocery life.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.2+59

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  collection: ^1.16.0
  path_provider: ^2.0.11
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  animations: ^2.0.7
  shimmer: ^2.0.0
  equatable: ^2.0.5
  url_launcher: ^6.1.6
  package_info_plus: 2.0.0
  device_info_plus: ^7.0.0
  http: ^0.13.5

  # reorderables: ^0.3.2
  # fluttertoast: ^8.0.3
  # infinite_scroll_pagination: ^3.1.0
  responsive_builder: ^0.4.3
  dynamic_color: ^1.5.4

  azlistview: ^2.0.0
  flutter_markdown: ^0.6.12
  tuple: ^2.0.1
  charts_flutter: ^0.12.0
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  file_picker: ^5.2.1
  photo_view: ^0.14.0
  share_handler: ^0.0.16
  reorderables: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.19.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Localization generation
  generate: true

  assets:
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#20AC64"
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
  ios: true
  remove_alpha_ios: true
